name: finapp
description: App for managing finances.
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  jwt_decode: ^0.3.1
  google_nav_bar: ^5.0.5
  flutter_login: 4.0.0
  fl_chart: ^0.36.1
  lazy_load_scrollview: ^1.3.0
  carousel_slider: ^4.0.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  flutter_dotenv: ^5.0.2
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
