name: finapp
description: App for managing finances.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  flutter_spinkit: "^4.1.2"
  intl: ^0.16.1
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  jwt_decode: ^0.3.1
  google_nav_bar: ^5.0.5
  flutter_login: ^1.1.0
  flutter_offline: "^2.0.0"
  timelines: ^0.1.0
  flutter_beautiful_popup: ^1.5.0
  fl_chart: ^0.36.1
  syncfusion_flutter_datagrid: ^19.1.67-beta
  lazy_load_scrollview: ^1.3.0
  flutter_launcher_icons: "^0.8.0"
  slide_to_confirm: ^0.0.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/