name: finapp
description: App for managing finances.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  flutter_spinkit: "^4.1.2"
  intl: ^0.16.1
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  jwt_decode: ^0.3.1
  google_nav_bar: ^5.0.5
  flutter_login: ^1.1.0
  flushbar: ^1.10.4
  flutter_offline: "^2.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proxima-nova-regular.ttf
        - asset: assets/fonts/proxima-nova-bold.ttf
          weight: 700
