name: finapp
description: App for managing finances.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  http: any
  flutter_mobile_vision: ^0.1.3
  flutter_spinkit: "^4.1.2"
  intl: ^0.16.1
  dio: ^4.0.0
  flutter_session: ^0.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proxima-nova-regular.ttf
        - asset: assets/fonts/proxima-nova-bold.ttf
          weight: 700
